In [1]:
!pip install requests beautifulsoup4 pandas

Requirement already satisfied: requests in d:\down\anaconda\lib\site-packages (2.32.5)
Requirement already satisfied: beautifulsoup4 in d:\down\anaconda\lib\site-packages (4.13.5)
Requirement already satisfied: pandas in d:\down\anaconda\lib\site-packages (2.3.3)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\down\anaconda\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in d:\down\anaconda\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\down\anaconda\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in d:\down\anaconda\lib\site-packages (from requests) (2025.11.12)
Requirement already satisfied: soupsieve>1.2 in d:\down\anaconda\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in d:\down\anaconda\lib\site-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: numpy>=1.26.0 in d:\down\anaconda\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\down\anaconda\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in d:\down\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in d:\down\anaconda\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in d:\down\anaconda\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
url = "https://books.toscrape.com/"

In [5]:
response = requests.get(url)

In [6]:
print(response.status_code)

200

In [7]:
soup = BeautifulSoup(response.text, "html.parser")

In [8]:
books = soup.find_all("article", class_="product_pod")

In [9]:
titles = []
prices = []
availability = []
ratings = []
links = []

In [10]:
for book in books:
    title = book.h3.a["title"]
    price = book.find("p", class_="price_color").text
    stock = book.find("p", class_="instock availability").text.strip()
    rating = book.find("p")["class"][1]
    link = "https://books.toscrape.com/catalogue/" + book.h3.a["href"]

    titles.append(title)
    prices.append(price)
    availability.append(stock)
    ratings.append(rating)
    links.append(link)

In [11]:
print(titles[:5])

['A Light in the Attic', 'Tipping the Velvet', 'Soumission', 'Sharp Objects', 'Sapiens: A Brief History of Humankind']

In [12]:
print(prices[:5])

['Â£51.77', 'Â£53.74', 'Â£50.10', 'Â£47.82', 'Â£54.23']

In [13]:
df = pd.DataFrame({
    "Title": titles,
    "Price": prices,
    "Availability": availability,
    "Rating": ratings,
    "Product Link": links
})

In [14]:
df.head()

,Title,Price,Availability,Rating,Product Link
0,A Light in the Attic,Â£51.77,In stock,Three,https://books.toscrape.com/catalogue/catalogue...
1,Tipping the Velvet,Â£53.74,In stock,One,https://books.toscrape.com/catalogue/catalogue...
2,Soumission,Â£50.10,In stock,One,https://books.toscrape.com/catalogue/catalogue...
3,Sharp Objects,Â£47.82,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five,https://books.toscrape.com/catalogue/catalogue...

In [15]:
df

,Title,Price,Availability,Rating,Product Link
0,A Light in the Attic,Â£51.77,In stock,Three,https://books.toscrape.com/catalogue/catalogue...
1,Tipping the Velvet,Â£53.74,In stock,One,https://books.toscrape.com/catalogue/catalogue...
2,Soumission,Â£50.10,In stock,One,https://books.toscrape.com/catalogue/catalogue...
3,Sharp Objects,Â£47.82,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five,https://books.toscrape.com/catalogue/catalogue...
5,The Requiem Red,Â£22.65,In stock,One,https://books.toscrape.com/catalogue/catalogue...
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,In stock,Three,https://books.toscrape.com/catalogue/catalogue...
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
9,The Black Maria,Â£52.15,In stock,One,https://books.toscrape.com/catalogue/catalogue...
10,"Starving Hearts (Triangular Trade Trilogy, #1)",Â£13.99,In stock,Two,https://books.toscrape.com/catalogue/catalogue...
11,Shakespeare's Sonnets,Â£20.66,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
12,Set Me Free,Â£17.46,In stock,Five,https://books.toscrape.com/catalogue/catalogue...
13,Scott Pilgrim's Precious Little Life (Scott Pi...,Â£52.29,In stock,Five,https://books.toscrape.com/catalogue/catalogue...
14,Rip it Up and Start Again,Â£35.02,In stock,Five,https://books.toscrape.com/catalogue/catalogue...
15,Our Band Could Be Your Life: Scenes from the A...,Â£57.25,In stock,Three,https://books.toscrape.com/catalogue/catalogue...
16,Olio,Â£23.88,In stock,One,https://books.toscrape.com/catalogue/catalogue...
17,Mesaerion: The Best Science Fiction Stories 18...,Â£37.59,In stock,One,https://books.toscrape.com/catalogue/catalogue...
18,Libertarianism for Beginners,Â£51.33,In stock,Two,https://books.toscrape.com/catalogue/catalogue...
19,It's Only the Himalayas,Â£45.17,In stock,Two,https://books.toscrape.com/catalogue/catalogue...

In [16]:
df.shape

(20, 5)

In [17]:
df.columns

Index(['Title', 'Price', 'Availability', 'Rating', 'Product Link'], dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Title         20 non-null     object
 1   Price         20 non-null     object
 2   Availability  20 non-null     object
 3   Rating        20 non-null     object
 4   Product Link  20 non-null     object
dtypes: object(5)
memory usage: 932.0+ bytes

In [20]:
df.to_csv("books_data.csv", index=False)

In [21]:
import os

print(os.getcwd())

C:\Users\DELL\Alpha

In [22]:
print("Total Books:", len(df))

Total Books: 20

In [23]:
df.head(10)

,Title,Price,Availability,Rating,Product Link
0,A Light in the Attic,Â£51.77,In stock,Three,https://books.toscrape.com/catalogue/catalogue...
1,Tipping the Velvet,Â£53.74,In stock,One,https://books.toscrape.com/catalogue/catalogue...
2,Soumission,Â£50.10,In stock,One,https://books.toscrape.com/catalogue/catalogue...
3,Sharp Objects,Â£47.82,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five,https://books.toscrape.com/catalogue/catalogue...
5,The Requiem Red,Â£22.65,In stock,One,https://books.toscrape.com/catalogue/catalogue...
6,The Dirty Little Secrets of Getting Your Dream...,Â£33.34,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
7,The Coming Woman: A Novel Based on the Life of...,Â£17.93,In stock,Three,https://books.toscrape.com/catalogue/catalogue...
8,The Boys in the Boat: Nine Americans and Their...,Â£22.60,In stock,Four,https://books.toscrape.com/catalogue/catalogue...
9,The Black Maria,Â£52.15,In stock,One,https://books.toscrape.com/catalogue/catalogue...

In [24]:
df["Rating"].value_counts()

Rating
One      6
Four     4
Five     4
Three    3
Two      3
Name: count, dtype: int64

In [25]:
df["Availability"].value_counts()

Availability
In stock    20
Name: count, dtype: int64

In [26]:
df.describe(include="all")

,Title,Price,Availability,Rating,Product Link
count,20,20,20,20,20
unique,20,20,1,5,20
top,A Light in the Attic,Â£51.77,In stock,One,https://books.toscrape.com/catalogue/catalogue...
freq,1,1,20,6,1

In [ ]:
This project demonstrates how to perform web scraping using python.
Data was collected from a public website using the requests and BeautifulSoup libraies.
The extracted information was organized into a Pandas Dataframe and saved as a CSV file for further analysis.
This project improved my understanding of HTML structure,data extraction and data handling in python.